import { Arc, Item, Listing, Quest, Trader } from "@/types";

export const items: Item[] = [
  {
    id: "item-1",
    name: "Arc Alloy",
    description: "High-grade alien alloy used in advanced crafting.",
    item_type: "Advanced Material",
    icon: "https://cdn.metaforge.app/arc-raiders/items/arc-alloy.webp",
    rarity: "rare",
    value: 520,
    stat_block: { stackSize: 20, weight: 0.8 },
  },
  {
    id: "item-2",
    name: "Plasma Core",
    description: "Rare power source capable of fueling heavy machinery.",
    item_type: "Power Source",
    icon: "https://cdn.metaforge.app/arc-raiders/items/plasma-core.webp",
    rarity: "legendary",
    value: 1500,
    stat_block: { stackSize: 5, weight: 1.2 },
  },
  {
    id: "item-3",
    name: "Adrenaline Shot",
    description: "Instantly restores stamina and increases sprint speed briefly.",
    item_type: "Consumable",
    icon: "https://cdn.metaforge.app/arc-raiders/items/adrenaline-shot.webp",
    rarity: "uncommon",
    value: 180,
    stat_block: { stackSize: 10, weight: 0.1, duration: 20 },
  },
  {
    id: "item-4",
    name: "Med Kit",
    description: "Full medical kit for field treatment.",
    item_type: "Medical",
    icon: "https://cdn.metaforge.app/arc-raiders/items/medical-supplies.webp",
    rarity: "rare",
    value: 420,
    stat_block: { stackSize: 3, weight: 0.6, healing: 75 },
  },
  {
    id: "item-5",
    name: "Circuit Board",
    description: "Essential electronics component required for hideout upgrades.",
    item_type: "Component",
    icon: "https://cdn.metaforge.app/arc-raiders/items/circuit-board.webp",
    rarity: "rare",
    value: 360,
    stat_block: { stackSize: 15, weight: 0.2 },
  },
  {
    id: "item-6",
    name: "Steel Plate",
    description: "Reinforced plating used in armor repairs and crafting.",
    item_type: "Basic Material",
    icon: "https://cdn.metaforge.app/arc-raiders/items/steel-plate.webp",
    rarity: "uncommon",
    value: 210,
    stat_block: { stackSize: 20, weight: 1.1 },
  },
  {
    id: "item-7",
    name: "Energy Cell",
    description: "Powers energy-based weapons and tools.",
    item_type: "Ammunition",
    icon: "https://cdn.metaforge.app/arc-raiders/items/energy-cell.webp",
    rarity: "uncommon",
    value: 160,
    stat_block: { stackSize: 30, weight: 0.15 },
  },
  {
    id: "item-8",
    name: "Nano Fiber",
    description: "Advanced synthetic fiber for high-end crafting.",
    item_type: "Advanced Material",
    icon: "https://cdn.metaforge.app/arc-raiders/items/nano-fiber.webp",
    rarity: "epic",
    value: 950,
    stat_block: { stackSize: 10, weight: 0.35 },
  },
  {
    id: "item-9",
    name: "Weapon Blueprint: Striker",
    description: "Blueprint to craft the Striker rifle.",
    item_type: "Blueprint",
    icon: "https://placehold.co/80x80/1a1a2e/f97316?text=BP",
    rarity: "epic",
    value: 780,
    stat_block: { stackSize: 1, weight: 0.05 },
  },
  {
    id: "item-10",
    name: "Bandage",
    description: "Basic wound treatment; stops bleeding.",
    item_type: "Medical",
    icon: "https://cdn.metaforge.app/arc-raiders/items/bandage.webp",
    rarity: "common",
    value: 60,
    stat_block: { stackSize: 12, weight: 0.05, healing: 20 },
  },
  {
    id: "item-11",
    name: "Ammo Box",
    description: "Standard ballistic ammunition box.",
    item_type: "Ammunition",
    icon: "https://placehold.co/80x80/1a1a2e/f97316?text=AMMO",
    rarity: "common",
    value: 90,
    stat_block: { stackSize: 25, weight: 0.4 },
  },
  {
    id: "item-12",
    name: "Suppressor",
    description: "Reduces weapon report and muzzle flash.",
    item_type: "Attachment",
    icon: "https://placehold.co/80x80/1a1a2e/f97316?text=SUP",
    rarity: "rare",
    value: 410,
    stat_block: { stackSize: 2, weight: 0.3 },
  },
];

export const arcs: Arc[] = [
  {
    id: "arc-1",
    name: "Sentry",
    description: "Mobile defense ARC equipped with suppressive fire.",
    icon: "https://cdn.metaforge.app/arc-raiders/arcs/sentry.webp",
    image: "https://cdn.metaforge.app/arc-raiders/arcs/sentry.webp",
  },
  {
    id: "arc-2",
    name: "Crusher",
    description: "Heavy ARC that specializes in close-quarters control.",
    icon: "https://cdn.metaforge.app/arc-raiders/arcs/crusher.webp",
    image: "https://cdn.metaforge.app/arc-raiders/arcs/crusher.webp",
  },
  {
    id: "arc-3",
    name: "Warden",
    description: "Area denial ARC with crowd-control tools.",
    icon: "https://cdn.metaforge.app/arc-raiders/arcs/warden.webp",
    image: "https://cdn.metaforge.app/arc-raiders/arcs/warden.webp",
  },
  {
    id: "arc-4",
    name: "Skirmisher",
    description: "Fast reconnaissance ARC built for flanking and disruption.",
    icon: "https://cdn.metaforge.app/arc-raiders/arcs/skirmisher.webp",
    image: "https://cdn.metaforge.app/arc-raiders/arcs/skirmisher.webp",
  },
  {
    id: "arc-5",
    name: "Bulwark",
    description: "Shielded ARC that anchors defensive positions.",
    icon: "https://cdn.metaforge.app/arc-raiders/arcs/bulwark.webp",
    image: "https://cdn.metaforge.app/arc-raiders/arcs/bulwark.webp",
  },
];

export const quests: Quest[] = [
  {
    id: "quest-1",
    name: "First Raid Prep",
    objectives: ["Collect 5 Bandages", "Find 2 Arc Alloy", "Extract successfully"],
    xp: 750,
    rewards: [
      { item: { id: "item-10", name: "Bandage" }, quantity: "x5" },
      { item: { id: "item-1", name: "Arc Alloy" }, quantity: "x1" },
    ],
  },
  {
    id: "quest-2",
    name: "Power Issues",
    objectives: ["Loot 3 Energy Cells", "Deliver to Engineer"],
    xp: 920,
    rewards: [{ item: { id: "item-7", name: "Energy Cell" }, quantity: "x3" }],
  },
  {
    id: "quest-3",
    name: "Blueprint Recovery",
    objectives: ["Retrieve Weapon Blueprint", "Extract through North Exit"],
    xp: 1100,
    rewards: [{ item: { id: "item-9", name: "Weapon Blueprint: Striker" }, quantity: "x1" }],
  },
];

export const traders: Trader[] = [
  {
    id: "trader-1",
    name: "Mara",
    description: "Specializes in medical and survival supplies.",
    image: "https://placehold.co/200x200/1a1a2e/f97316?text=Mara",
    items: [
      { id: "item-3", name: "Adrenaline Shot", trader_price: 220, rarity: "uncommon", item_type: "Consumable" },
      { id: "item-4", name: "Med Kit", trader_price: 480, rarity: "rare", item_type: "Medical" },
      { id: "item-10", name: "Bandage", trader_price: 70, rarity: "common", item_type: "Medical" },
    ],
  },
  {
    id: "trader-2",
    name: "Kova",
    description: "Dealer in advanced materials and components.",
    image: "https://placehold.co/200x200/1a1a2e/f97316?text=Kova",
    items: [
      { id: "item-1", name: "Arc Alloy", trader_price: 600, rarity: "rare", item_type: "Advanced Material" },
      { id: "item-5", name: "Circuit Board", trader_price: 400, rarity: "rare", item_type: "Component" },
      { id: "item-8", name: "Nano Fiber", trader_price: 1100, rarity: "epic", item_type: "Advanced Material" },
    ],
  },
  {
    id: "trader-3",
    name: "Rix",
    description: "Weaponsmith with select attachments and ammo.",
    image: "https://placehold.co/200x200/1a1a2e/f97316?text=Rix",
    items: [
      { id: "item-11", name: "Ammo Box", trader_price: 120, rarity: "common", item_type: "Ammunition" },
      { id: "item-12", name: "Suppressor", trader_price: 460, rarity: "rare", item_type: "Attachment" },
      { id: "item-7", name: "Energy Cell", trader_price: 190, rarity: "uncommon", item_type: "Ammunition" },
    ],
  },
];

export const listings: Listing[] = [
  {
    id: "listing-1",
    user: { id: "u1", username: "GreyFox" },
    type: "WTS",
    item: items[0],
    quantity: 6,
    price_type: "seeds",
    price: 520,
    created_at: new Date("2024-12-15").toISOString(),
    status: "active",
  },
  {
    id: "listing-2",
    user: { id: "u2", username: "Nyx" },
    type: "WTB",
    item: items[7],
    quantity: 3,
    price_type: "seeds",
    price: 1000,
    created_at: new Date("2024-12-16").toISOString(),
    status: "active",
  },
  {
    id: "listing-3",
    user: { id: "u3", username: "Patch" },
    type: "WTS",
    item: items[2],
    quantity: 10,
    price_type: "seeds",
    price: 190,
    created_at: new Date("2024-12-17").toISOString(),
    status: "active",
  },
  {
    id: "listing-4",
    user: { id: "u4", username: "Tala" },
    type: "WTB",
    item: items[4],
    quantity: 4,
    price_type: "seeds",
    price: 380,
    created_at: new Date("2024-12-18").toISOString(),
    status: "active",
  },
  {
    id: "listing-5",
    user: { id: "u5", username: "Axiom" },
    type: "WTS",
    item: items[8],
    quantity: 1,
    price_type: "seeds",
    price: 820,
    created_at: new Date("2024-12-19").toISOString(),
    status: "active",
  },
];
